version: "2"
services:
  web:
    build: .
    container_name: web_app
    restart: unless-stopped
    ports:
      - '8080:8080'
    privileged: true
    depends_on:
      - redis

  redis:
    image: redis:5
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'