version: "2"
services:
  web:
    build: .
    container_name: web_app
    restart: always
    ports:
      - '80:80'
    depends_on:
      - redis

  redis:
    image: redis:5
    container_name: redis
    restart: always
    ports:
      - '6379:6379'