version: "2"
services:
  web:
    build: .
    container_name: web_app
    restart: always
    ports:
      - '8080:8080'
    devices:
      - '/dev/gpiomem :/dev/gpiomem'
    depends_on:
      - redis

  redis:
    image: redis:5
    container_name: redis
    restart: always
    ports:
      - '6379:6379'